services:
  whatsapp:
    build: ./node
    container_name: broadcastio-whatsapp
    ports:
      - "3000:3000"
    volumes:
      - ./node/.wwebjs_auth:/app/.wwebjs_auth
      - ./node/qr:/app/qr
      - ./node/src:/app/src
      - ./python/shared_files:/app/shared_files
    restart: unless-stopped

  # python:
  #   build: ./python
  #   container_name: broadcastio-python
  #   depends_on:
  #     - whatsapp
  #   environment:
  #     WHATSAPP_BASE_URL: http://whatsapp:3000
